### ISSUE TITLE
improve formatting

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/modelica-builder#13]
No special formatting is currently done when inserting/replacing code.

Might be worth having a configurable option for formatting style, or to just follow some existing style guide.

Resources:
- https://github.com/ibpsa/modelica-ibpsa/wiki/Style-Guide
- https://stackoverflow.com/questions/14163386/modelica-style-guide

**Comment by nllong** [comment]
won't fix for now. Feel free to create a PR resolving this issue--
