### ISSUE TITLE
Needed some help regarding creating a new selector

### ISSUE THREAD

**Issue by Kinshuk94** [urbanopt/modelica-builder#25]
Hello I am bit new to this Modelica-builder I really appreciate the work that you guys are doing. In my project implementation there is a requirement to only select some of the replaceable parameters. I was trying to add a new selector but it looks like I am unable to add a class to the selector file. The same happens with the model file as I am unable to add a new function to it. Could you please help me out on this also if you could give me some hint it would be great on how I could only extract the replaceable parameters as I was also trying to make changes to the inbuilt selector but it looks like it does not work.
Thanks in advance.

**Comment by macintoshpie** [comment]
We've not updated our README, but in case you didn't see it we provide a higher level API for modifying the modelica files through the Model class, you can find a lot of examples here:
https://github.com/urbanopt/modelica-builder/blob/develop/tests/test_model.py

You should be able to just subclass the `Selector` class from modelica_builder.selector to create a new selector, you can find an example here:
https://github.com/urbanopt/modelica-builder/blob/de604027d555b5ad5d6acd1a55e3634f275edf70/modelica_builder/selector.py#L94

Then you would just need to create a transformation and add it to the model. Find a sample below, hope this helps!
```python
from modelica_builder.edit import Edit
from modelica_builder.selector import Selector
from modelica_builder.transformation import SimpleTransformation

class MySelector(Selector):
    # implement class here

selector = MySelector()
transformation = SimpleTransformation(selector, Edit.make_replace('replacement text'))

my_mo_model = Model('my_modelica_file.mo')
my_mo_model.add(transformation)
my_mo_model.save_as('result.mo')
```

**Comment by macintoshpie** [comment]
@Kinshuk94 Closing this issue, let us know if you have any other questions.
