### ISSUE TITLE
Fix issues reading files which include CRLF

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/modelica-builder#35]
Modelica-builder does not work for files that use CRLF (`\r\n`) instead of only newlines (`\n`). Modelica-builder should work for either line delimiter.

**Comment by mzhen77** [comment]
Any chance to get that fix done? This bug blocks using of "Modelica-builder" on Windows.
Thanks!

**Comment by macintoshpie** [comment]
@mzhen77 Release 0.2.0 includes a fix for this. Let us know if the issue persists

**Comment by mzhen77** [comment]
@macintoshpie It works. Thank you very much!
